/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo
package public
package user_logs

import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import net.wiringbits.typo.customtypes.TypoUUID
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typo.dsl.Bijection

/** Type for the primary key of table `public.user_logs` */
case class UserLogsId(value: TypoUUID) extends AnyVal
object UserLogsId {
  implicit lazy val arrayColumn: Column[Array[UserLogsId]] = Column.columnToArray(column, implicitly)
  implicit lazy val arrayToStatement: ToStatement[Array[UserLogsId]] = TypoUUID.arrayToStatement.contramap(_.map(_.value))
  implicit lazy val bijection: Bijection[UserLogsId, TypoUUID] = Bijection[UserLogsId, TypoUUID](_.value)(UserLogsId.apply)
  implicit lazy val column: Column[UserLogsId] = TypoUUID.column.map(UserLogsId.apply)
  implicit def ordering(implicit O0: Ordering[TypoUUID]): Ordering[UserLogsId] = Ordering.by(_.value)
  implicit lazy val parameterMetadata: ParameterMetaData[UserLogsId] = new ParameterMetaData[UserLogsId] {
    override def sqlType: String = TypoUUID.parameterMetadata.sqlType
    override def jdbcType: Int = TypoUUID.parameterMetadata.jdbcType
  }
  implicit lazy val reads: Reads[UserLogsId] = TypoUUID.reads.map(UserLogsId.apply)
  implicit lazy val toStatement: ToStatement[UserLogsId] = TypoUUID.toStatement.contramap(_.value)
  implicit lazy val writes: Writes[UserLogsId] = TypoUUID.writes.contramap(_.value)
}
