/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package user_tokens

import anorm.Column
import anorm.RowParser
import anorm.Success
import java.time.Instant
import java.util.UUID
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

case class UserTokensRow(
    userTokenId: /* user-picked */ UUID,
    token: String,
    tokenType: String,
    createdAt: /* user-picked */ Instant,
    expiresAt: /* user-picked */ Instant,
    /** Points to [[users.UsersRow.userId]] */
    userId: /* user-picked */ UUID
)

object UserTokensRow {
  implicit lazy val reads: Reads[UserTokensRow] = Reads[UserTokensRow](json =>
    JsResult.fromTry(
      Try(
        UserTokensRow(
          userTokenId = json.\("user_token_id").as(Reads.uuidReads),
          token = json.\("token").as(Reads.StringReads),
          tokenType = json.\("token_type").as(Reads.StringReads),
          createdAt = json.\("created_at").as(implicitly[Reads[Instant]]),
          expiresAt = json.\("expires_at").as(implicitly[Reads[Instant]]),
          userId = json.\("user_id").as(Reads.uuidReads)
        )
      )
    )
  )
  def rowParser(idx: Int): RowParser[UserTokensRow] = RowParser[UserTokensRow] { row =>
    Success(
      UserTokensRow(
        userTokenId = row(idx + 0)(Column.columnToUUID),
        token = row(idx + 1)(Column.columnToString),
        tokenType = row(idx + 2)(Column.columnToString),
        createdAt = row(idx + 3)(Implicits.instantColumn),
        expiresAt = row(idx + 4)(Implicits.instantColumn),
        userId = row(idx + 5)(Column.columnToUUID)
      )
    )
  }
  implicit lazy val writes: OWrites[UserTokensRow] = OWrites[UserTokensRow](o =>
    new JsObject(
      ListMap[String, JsValue](
        "user_token_id" -> Writes.UuidWrites.writes(o.userTokenId),
        "token" -> Writes.StringWrites.writes(o.token),
        "token_type" -> Writes.StringWrites.writes(o.tokenType),
        "created_at" -> implicitly[Writes[Instant]].writes(o.createdAt),
        "expires_at" -> implicitly[Writes[Instant]].writes(o.expiresAt),
        "user_id" -> Writes.UuidWrites.writes(o.userId)
      )
    )
  )
}
