/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package user_tokens

import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.UUIDCustom
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.IdField

trait UserTokensFields[Row] {
  val userTokenId: IdField[ /* user-picked */ UUIDCustom, Row]
  val token: Field[String, Row]
  val tokenType: Field[String, Row]
  val createdAt: Field[ /* user-picked */ InstantCustom, Row]
  val expiresAt: Field[ /* user-picked */ InstantCustom, Row]
  val userId: Field[ /* user-picked */ UUIDCustom, Row]
}
object UserTokensFields extends UserTokensStructure[UserTokensRow](None, identity, (_, x) => x)
