/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo
package public
package user_tokens

import anorm.Column
import anorm.RowParser
import anorm.Success
import net.wiringbits.typo.customtypes.TypoOffsetDateTime
import net.wiringbits.typo.public.users.UsersId
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

case class UserTokensRow(
  userTokenId: UserTokensId,
  token: String,
  tokenType: String,
  createdAt: TypoOffsetDateTime,
  expiresAt: TypoOffsetDateTime,
  /** Points to [[users.UsersRow.userId]] */
  userId: UsersId
)

object UserTokensRow {
  implicit lazy val reads: Reads[UserTokensRow] = Reads[UserTokensRow](json => JsResult.fromTry(
      Try(
        UserTokensRow(
          userTokenId = json.\("user_token_id").as(UserTokensId.reads),
          token = json.\("token").as(Reads.StringReads),
          tokenType = json.\("token_type").as(Reads.StringReads),
          createdAt = json.\("created_at").as(TypoOffsetDateTime.reads),
          expiresAt = json.\("expires_at").as(TypoOffsetDateTime.reads),
          userId = json.\("user_id").as(UsersId.reads)
        )
      )
    ),
  )
  def rowParser(idx: Int): RowParser[UserTokensRow] = RowParser[UserTokensRow] { row =>
    Success(
      UserTokensRow(
        userTokenId = row(idx + 0)(UserTokensId.column),
        token = row(idx + 1)(Column.columnToString),
        tokenType = row(idx + 2)(Column.columnToString),
        createdAt = row(idx + 3)(TypoOffsetDateTime.column),
        expiresAt = row(idx + 4)(TypoOffsetDateTime.column),
        userId = row(idx + 5)(UsersId.column)
      )
    )
  }
  implicit lazy val writes: OWrites[UserTokensRow] = OWrites[UserTokensRow](o =>
    new JsObject(ListMap[String, JsValue](
      "user_token_id" -> UserTokensId.writes.writes(o.userTokenId),
      "token" -> Writes.StringWrites.writes(o.token),
      "token_type" -> Writes.StringWrites.writes(o.tokenType),
      "created_at" -> TypoOffsetDateTime.writes.writes(o.createdAt),
      "expires_at" -> TypoOffsetDateTime.writes.writes(o.expiresAt),
      "user_id" -> UsersId.writes.writes(o.userId)
    ))
  )
}
