/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo
package public
package user_tokens

import net.wiringbits.typo.customtypes.TypoOffsetDateTime
import net.wiringbits.typo.public.users.UsersId
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.IdField

trait UserTokensFields[Row] {
  val userTokenId: IdField[UserTokensId, Row]
  val token: Field[String, Row]
  val tokenType: Field[String, Row]
  val createdAt: Field[TypoOffsetDateTime, Row]
  val expiresAt: Field[TypoOffsetDateTime, Row]
  val userId: Field[UsersId, Row]
}
object UserTokensFields extends UserTokensStructure[UserTokensRow](None, identity, (_, x) => x)

