/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package user_logs

import anorm.ToStatement
import java.sql.Connection
import net.wiringbits.common.models.id.UserLogId
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder

trait UserLogsRepo {
  def delete(userLogId: /* user-picked */ UserLogId)(implicit c: Connection): Boolean
  def delete: DeleteBuilder[UserLogsFields, UserLogsRow]
  def insert(unsaved: UserLogsRow)(implicit c: Connection): UserLogsRow
  def insert(unsaved: UserLogsRowUnsaved)(implicit c: Connection): UserLogsRow
  def select: SelectBuilder[UserLogsFields, UserLogsRow]
  def selectAll(implicit c: Connection): List[UserLogsRow]
  def selectById(userLogId: /* user-picked */ UserLogId)(implicit c: Connection): Option[UserLogsRow]
  def selectByIds(
      userLogIds: Array[ /* user-picked */ UserLogId]
  )(implicit c: Connection, toStatement: ToStatement[Array[ /* user-picked */ UserLogId]]): List[UserLogsRow]
  def update(row: UserLogsRow)(implicit c: Connection): Boolean
  def update: UpdateBuilder[UserLogsFields, UserLogsRow]
  def upsert(unsaved: UserLogsRow)(implicit c: Connection): UserLogsRow
}
