/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package user_logs

import java.time.Instant
import java.util.UUID
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.IdField

trait UserLogsFields[Row] {
  val userLogId: IdField[ /* user-picked */ UUID, Row]
  val userId: Field[ /* user-picked */ UUID, Row]
  val message: Field[String, Row]
  val createdAt: Field[ /* user-picked */ Instant, Row]
}
object UserLogsFields extends UserLogsStructure[UserLogsRow](None, identity, (_, x) => x)
