/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo_generated
package public
package user_logs

import net.wiringbits.typo_generated.customtypes.TypoOffsetDateTime
import net.wiringbits.typo_generated.public.users.UsersId
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.IdField

trait UserLogsFields[Row] {
  val userLogId: IdField[UserLogsId, Row]
  val userId: Field[UsersId, Row]
  val message: Field[String, Row]
  val createdAt: Field[TypoOffsetDateTime, Row]
}
object UserLogsFields extends UserLogsStructure[UserLogsRow](None, identity, (_, x) => x)

