/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package user_logs

import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.id.UserId
import net.wiringbits.common.models.id.UserLogId
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLikeNoHkt
import typo.dsl.SqlExpr.IdField
import typo.dsl.Structure.Relation

class UserLogsStructure[Row](
    val prefix: Option[String],
    val extract: Row => UserLogsRow,
    val merge: (Row, UserLogsRow) => Row
) extends Relation[UserLogsFields, UserLogsRow, Row]
    with UserLogsFields[Row] { outer =>

  override val userLogId = new IdField[ /* user-picked */ UserLogId, Row](prefix, "user_log_id", None, Some("uuid"))(
    x => extract(x).userLogId,
    (row, value) => merge(row, extract(row).copy(userLogId = value))
  )
  override val userId = new Field[ /* user-picked */ UserId, Row](prefix, "user_id", None, Some("uuid"))(
    x => extract(x).userId,
    (row, value) => merge(row, extract(row).copy(userId = value))
  )
  override val message = new Field[String, Row](prefix, "message", None, None)(
    x => extract(x).message,
    (row, value) => merge(row, extract(row).copy(message = value))
  )
  override val createdAt =
    new Field[ /* user-picked */ InstantCustom, Row](prefix, "created_at", Some("text"), Some("timestamptz"))(
      x => extract(x).createdAt,
      (row, value) => merge(row, extract(row).copy(createdAt = value))
    )

  override val columns: List[FieldLikeNoHkt[?, Row]] =
    List[FieldLikeNoHkt[?, Row]](userLogId, userId, message, createdAt)

  override def copy[NewRow](
      prefix: Option[String],
      extract: NewRow => UserLogsRow,
      merge: (NewRow, UserLogsRow) => NewRow
  ): UserLogsStructure[NewRow] =
    new UserLogsStructure(prefix, extract, merge)
}
