/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package user_logs

import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.id.UserId
import net.wiringbits.common.models.id.UserLogId
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.IdField

trait UserLogsFields[Row] {
  val userLogId: IdField[ /* user-picked */ UserLogId, Row]
  val userId: Field[ /* user-picked */ UserId, Row]
  val message: Field[String, Row]
  val createdAt: Field[ /* user-picked */ InstantCustom, Row]
}
object UserLogsFields extends UserLogsStructure[UserLogsRow](None, identity, (_, x) => x)
