/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo_generated
package public
package user_logs

import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.UUIDCustom
import net.wiringbits.typo_generated.customtypes.Defaulted
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** This class corresponds to a row in table `public.user_logs` which has not been persisted yet */
case class UserLogsRowUnsaved(
  userLogId: /* user-picked */ UUIDCustom,
  /** Points to [[users.UsersRow.userId]] */
  userId: /* user-picked */ UUIDCustom,
  message: String,
  /** Default: now() */
  createdAt: Defaulted[/* user-picked */ InstantCustom] = Defaulted.UseDefault
) {
  def toRow(createdAtDefault: => /* user-picked */ InstantCustom): UserLogsRow =
    UserLogsRow(
      userLogId = userLogId,
      userId = userId,
      message = message,
      createdAt = createdAt match {
                    case Defaulted.UseDefault => createdAtDefault
                    case Defaulted.Provided(value) => value
                  }
    )
}
object UserLogsRowUnsaved {
  implicit lazy val reads: Reads[UserLogsRowUnsaved] = Reads[UserLogsRowUnsaved](json => JsResult.fromTry(
      Try(
        UserLogsRowUnsaved(
          userLogId = json.\("user_log_id").as(implicitly[Reads[UUIDCustom]]),
          userId = json.\("user_id").as(implicitly[Reads[UUIDCustom]]),
          message = json.\("message").as(Reads.StringReads),
          createdAt = json.\("created_at").as(Defaulted.reads(implicitly[Reads[InstantCustom]]))
        )
      )
    ),
  )
  implicit lazy val writes: OWrites[UserLogsRowUnsaved] = OWrites[UserLogsRowUnsaved](o =>
    new JsObject(ListMap[String, JsValue](
      "user_log_id" -> implicitly[Writes[UUIDCustom]].writes(o.userLogId),
      "user_id" -> implicitly[Writes[UUIDCustom]].writes(o.userId),
      "message" -> Writes.StringWrites.writes(o.message),
      "created_at" -> Defaulted.writes(implicitly[Writes[InstantCustom]]).writes(o.createdAt)
    ))
  )
}
