/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package users

import anorm.Column
import anorm.RowParser
import anorm.Success
import java.time.Instant
import java.util.UUID
import net.wiringbits.common.models.Email
import net.wiringbits.common.models.Name
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

case class UsersRow(
    userId: /* user-picked */ UUID,
    name: /* user-picked */ Name,
    lastName: Option[String],
    email: /* user-picked */ Email,
    password: String,
    createdAt: /* user-picked */ Instant,
    verifiedOn: Option[ /* user-picked */ Instant]
)

object UsersRow {
  implicit lazy val reads: Reads[UsersRow] = Reads[UsersRow](json =>
    JsResult.fromTry(
      Try(
        UsersRow(
          userId = json.\("user_id").as(Reads.uuidReads),
          name = json.\("name").as(implicitly[Reads[Name]]),
          lastName = json.\("last_name").toOption.map(_.as(Reads.StringReads)),
          email = json.\("email").as(implicitly[Reads[Email]]),
          password = json.\("password").as(Reads.StringReads),
          createdAt = json.\("created_at").as(implicitly[Reads[Instant]]),
          verifiedOn = json.\("verified_on").toOption.map(_.as(implicitly[Reads[Instant]]))
        )
      )
    )
  )
  def rowParser(idx: Int): RowParser[UsersRow] = RowParser[UsersRow] { row =>
    Success(
      UsersRow(
        userId = row(idx + 0)(Column.columnToUUID),
        name = row(idx + 1)(implicitly[Column[Name]]),
        lastName = row(idx + 2)(Column.columnToOption(Column.columnToString)),
        email = row(idx + 3)(implicitly[Column[Email]]),
        password = row(idx + 4)(Column.columnToString),
        createdAt = row(idx + 5)(Implicits.instantColumn),
        verifiedOn = row(idx + 6)(Column.columnToOption(Implicits.instantColumn))
      )
    )
  }
  implicit lazy val writes: OWrites[UsersRow] = OWrites[UsersRow](o =>
    new JsObject(
      ListMap[String, JsValue](
        "user_id" -> Writes.UuidWrites.writes(o.userId),
        "name" -> implicitly[Writes[Name]].writes(o.name),
        "last_name" -> Writes.OptionWrites(Writes.StringWrites).writes(o.lastName),
        "email" -> implicitly[Writes[Email]].writes(o.email),
        "password" -> Writes.StringWrites.writes(o.password),
        "created_at" -> implicitly[Writes[Instant]].writes(o.createdAt),
        "verified_on" -> Writes.OptionWrites(implicitly[Writes[Instant]]).writes(o.verifiedOn)
      )
    )
  )
}
