/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package users

import anorm.Column
import anorm.RowParser
import anorm.Success
import net.wiringbits.common.models.Email
import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.Name
import net.wiringbits.common.models.id.UserId
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

case class UsersRow(
    userId: /* user-picked */ UserId,
    name: /* user-picked */ Name,
    lastName: Option[String],
    email: /* user-picked */ Email,
    password: String,
    createdAt: /* user-picked */ InstantCustom,
    verifiedOn: Option[ /* user-picked */ InstantCustom]
)

object UsersRow {
  implicit lazy val reads: Reads[UsersRow] = Reads[UsersRow](json =>
    JsResult.fromTry(
      Try(
        UsersRow(
          userId = json.\("user_id").as(implicitly[Reads[UserId]]),
          name = json.\("name").as(implicitly[Reads[Name]]),
          lastName = json.\("last_name").toOption.map(_.as(Reads.StringReads)),
          email = json.\("email").as(implicitly[Reads[Email]]),
          password = json.\("password").as(Reads.StringReads),
          createdAt = json.\("created_at").as(implicitly[Reads[InstantCustom]]),
          verifiedOn = json.\("verified_on").toOption.map(_.as(implicitly[Reads[InstantCustom]]))
        )
      )
    )
  )
  def rowParser(idx: Int): RowParser[UsersRow] = RowParser[UsersRow] { row =>
    Success(
      UsersRow(
        userId = row(idx + 0)(implicitly[Column[UserId]]),
        name = row(idx + 1)(implicitly[Column[Name]]),
        lastName = row(idx + 2)(Column.columnToOption(Column.columnToString)),
        email = row(idx + 3)(implicitly[Column[Email]]),
        password = row(idx + 4)(Column.columnToString),
        createdAt = row(idx + 5)(implicitly[Column[InstantCustom]]),
        verifiedOn = row(idx + 6)(Column.columnToOption(implicitly[Column[InstantCustom]]))
      )
    )
  }
  implicit lazy val writes: OWrites[UsersRow] = OWrites[UsersRow](o =>
    new JsObject(
      ListMap[String, JsValue](
        "user_id" -> implicitly[Writes[UserId]].writes(o.userId),
        "name" -> implicitly[Writes[Name]].writes(o.name),
        "last_name" -> Writes.OptionWrites(Writes.StringWrites).writes(o.lastName),
        "email" -> implicitly[Writes[Email]].writes(o.email),
        "password" -> Writes.StringWrites.writes(o.password),
        "created_at" -> implicitly[Writes[InstantCustom]].writes(o.createdAt),
        "verified_on" -> Writes.OptionWrites(implicitly[Writes[InstantCustom]]).writes(o.verifiedOn)
      )
    )
  )
}
