/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package users

import net.wiringbits.common.models.Email
import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.Name
import net.wiringbits.common.models.id.UserId
import net.wiringbits.typo_generated.customtypes.Defaulted
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** This class corresponds to a row in table `public.users` which has not been persisted yet */
case class UsersRowUnsaved(
    userId: /* user-picked */ UserId,
    name: /* user-picked */ Name,
    lastName: Option[String],
    email: /* user-picked */ Email,
    password: String,
    verifiedOn: Option[ /* user-picked */ InstantCustom],
    /** Default: now() */
    createdAt: Defaulted[ /* user-picked */ InstantCustom] = Defaulted.UseDefault
) {
  def toRow(createdAtDefault: => /* user-picked */ InstantCustom): UsersRow =
    UsersRow(
      userId = userId,
      name = name,
      lastName = lastName,
      email = email,
      password = password,
      verifiedOn = verifiedOn,
      createdAt = createdAt match {
        case Defaulted.UseDefault => createdAtDefault
        case Defaulted.Provided(value) => value
      }
    )
}
object UsersRowUnsaved {
  implicit lazy val reads: Reads[UsersRowUnsaved] = Reads[UsersRowUnsaved](json =>
    JsResult.fromTry(
      Try(
        UsersRowUnsaved(
          userId = json.\("user_id").as(implicitly[Reads[UserId]]),
          name = json.\("name").as(implicitly[Reads[Name]]),
          lastName = json.\("last_name").toOption.map(_.as(Reads.StringReads)),
          email = json.\("email").as(implicitly[Reads[Email]]),
          password = json.\("password").as(Reads.StringReads),
          verifiedOn = json.\("verified_on").toOption.map(_.as(implicitly[Reads[InstantCustom]])),
          createdAt = json.\("created_at").as(Defaulted.reads(implicitly[Reads[InstantCustom]]))
        )
      )
    )
  )
  implicit lazy val writes: OWrites[UsersRowUnsaved] = OWrites[UsersRowUnsaved](o =>
    new JsObject(
      ListMap[String, JsValue](
        "user_id" -> implicitly[Writes[UserId]].writes(o.userId),
        "name" -> implicitly[Writes[Name]].writes(o.name),
        "last_name" -> Writes.OptionWrites(Writes.StringWrites).writes(o.lastName),
        "email" -> implicitly[Writes[Email]].writes(o.email),
        "password" -> Writes.StringWrites.writes(o.password),
        "verified_on" -> Writes.OptionWrites(implicitly[Writes[InstantCustom]]).writes(o.verifiedOn),
        "created_at" -> Defaulted.writes(implicitly[Writes[InstantCustom]]).writes(o.createdAt)
      )
    )
  )
}
