/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package users

import net.wiringbits.typo_generated.customtypes.TypoOffsetDateTime
import net.wiringbits.typo_generated.customtypes.TypoUnknownCitext
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.IdField
import typo.dsl.SqlExpr.OptField

trait UsersFields[Row] {
  val userId: IdField[UsersId, Row]
  val name: Field[String, Row]
  val lastName: OptField[String, Row]
  val email: Field[TypoUnknownCitext, Row]
  val password: Field[String, Row]
  val createdAt: Field[TypoOffsetDateTime, Row]
  val verifiedOn: OptField[TypoOffsetDateTime, Row]
}
object UsersFields extends UsersStructure[UsersRow](None, identity, (_, x) => x)
