/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package users

import net.wiringbits.common.models.Email
import net.wiringbits.common.models.InstantCustom
import net.wiringbits.common.models.Name
import net.wiringbits.common.models.UUIDCustom
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLikeNoHkt
import typo.dsl.SqlExpr.IdField
import typo.dsl.SqlExpr.OptField
import typo.dsl.Structure.Relation

class UsersStructure[Row](val prefix: Option[String], val extract: Row => UsersRow, val merge: (Row, UsersRow) => Row)
    extends Relation[UsersFields, UsersRow, Row]
    with UsersFields[Row] { outer =>

  override val userId = new IdField[ /* user-picked */ UUIDCustom, Row](prefix, "user_id", None, Some("uuid"))(
    x => extract(x).userId,
    (row, value) => merge(row, extract(row).copy(userId = value))
  )
  override val name = new Field[ /* user-picked */ Name, Row](prefix, "name", None, None)(
    x => extract(x).name,
    (row, value) => merge(row, extract(row).copy(name = value))
  )
  override val lastName = new OptField[String, Row](prefix, "last_name", None, None)(
    x => extract(x).lastName,
    (row, value) => merge(row, extract(row).copy(lastName = value))
  )
  override val email = new Field[ /* user-picked */ Email, Row](prefix, "email", Some("text"), Some("citext"))(
    x => extract(x).email,
    (row, value) => merge(row, extract(row).copy(email = value))
  )
  override val password = new Field[String, Row](prefix, "password", None, None)(
    x => extract(x).password,
    (row, value) => merge(row, extract(row).copy(password = value))
  )
  override val createdAt =
    new Field[ /* user-picked */ InstantCustom, Row](prefix, "created_at", Some("text"), Some("timestamptz"))(
      x => extract(x).createdAt,
      (row, value) => merge(row, extract(row).copy(createdAt = value))
    )
  override val verifiedOn =
    new OptField[ /* user-picked */ InstantCustom, Row](prefix, "verified_on", Some("text"), Some("timestamptz"))(
      x => extract(x).verifiedOn,
      (row, value) => merge(row, extract(row).copy(verifiedOn = value))
    )

  override val columns: List[FieldLikeNoHkt[?, Row]] =
    List[FieldLikeNoHkt[?, Row]](userId, name, lastName, email, password, createdAt, verifiedOn)

  override def copy[NewRow](
      prefix: Option[String],
      extract: NewRow => UsersRow,
      merge: (NewRow, UsersRow) => NewRow
  ): UsersStructure[NewRow] =
    new UsersStructure(prefix, extract, merge)
}
