/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo_generated
package public
package users

import anorm.ToStatement
import java.sql.Connection
import net.wiringbits.common.models.Email
import net.wiringbits.common.models.UUIDCustom
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder

trait UsersRepo {
  def delete(userId: /* user-picked */ UUIDCustom)(implicit c: Connection): Boolean
  def delete: DeleteBuilder[UsersFields, UsersRow]
  def insert(unsaved: UsersRow)(implicit c: Connection): UsersRow
  def insert(unsaved: UsersRowUnsaved)(implicit c: Connection): UsersRow
  def select: SelectBuilder[UsersFields, UsersRow]
  def selectAll(implicit c: Connection): List[UsersRow]
  def selectById(userId: /* user-picked */ UUIDCustom)(implicit c: Connection): Option[UsersRow]
  def selectByIds(userIds: Array[/* user-picked */ UUIDCustom])(implicit c: Connection, toStatement: ToStatement[Array[/* user-picked */ UUIDCustom]]): List[UsersRow]
  def selectByUnique(email: /* user-picked */ Email)(implicit c: Connection): Option[UsersRow]
  def update(row: UsersRow)(implicit c: Connection): Boolean
  def update: UpdateBuilder[UsersFields, UsersRow]
  def upsert(unsaved: UsersRow)(implicit c: Connection): UsersRow
}
