@startuml
Title Wiringbits Scala WebApp Template - Server Architecture - DAOs

skinparam {
    linetype ortho
}

skinparam component {
  BackgroundColor LightBlue
}
skinparam rectangle {
  BackgroundColor White
}

rectangle Controllers {
    rectangle Actions {
        rectangle Services {
            rectangle ExternalApis {
                rectangle ExternalApiClients {
                    rectangle ExternalApiModels
                }
            }
            rectangle Repositories {
                component DAOs {
                    rectangle DataModels
                }
            }
        }
    }
}
@enduml
