@startuml
Title Wiringbits Scala WebApp Template - Server Architecture - Repositories

skinparam {
    linetype ortho
}

skinparam component {
  BackgroundColor LightBlue
}
skinparam rectangle {
  BackgroundColor White
}

rectangle Controllers {
    rectangle Actions {
        rectangle Services {
            rectangle ExternalApis {
                rectangle ExternalApiClients {
                    rectangle ExternalApiModels
                }
            }
            component Repositories {
                rectangle DAOs {
                    rectangle DataModels
                }
            }
        }
    }
}
@enduml
