/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package background_jobs

import anorm.Column
import anorm.RowParser
import anorm.Success
import java.time.Instant
import java.util.UUID
import net.wiringbits.typo_generated.customtypes.TypoJsonb
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

case class BackgroundJobsRow(
    backgroundJobId: /* user-picked */ UUID,
    `type`: String,
    payload: TypoJsonb,
    status: String,
    statusDetails: Option[String],
    errorCount: Option[Int],
    executeAt: /* user-picked */ Instant,
    createdAt: /* user-picked */ Instant,
    updatedAt: /* user-picked */ Instant
)

object BackgroundJobsRow {
  implicit lazy val reads: Reads[BackgroundJobsRow] = Reads[BackgroundJobsRow](json =>
    JsResult.fromTry(
      Try(
        BackgroundJobsRow(
          backgroundJobId = json.\("background_job_id").as(Reads.uuidReads),
          `type` = json.\("type").as(Reads.StringReads),
          payload = json.\("payload").as(TypoJsonb.reads),
          status = json.\("status").as(Reads.StringReads),
          statusDetails = json.\("status_details").toOption.map(_.as(Reads.StringReads)),
          errorCount = json.\("error_count").toOption.map(_.as(Reads.IntReads)),
          executeAt = json.\("execute_at").as(implicitly[Reads[Instant]]),
          createdAt = json.\("created_at").as(implicitly[Reads[Instant]]),
          updatedAt = json.\("updated_at").as(implicitly[Reads[Instant]])
        )
      )
    )
  )
  def rowParser(idx: Int): RowParser[BackgroundJobsRow] = RowParser[BackgroundJobsRow] { row =>
    Success(
      BackgroundJobsRow(
        backgroundJobId = row(idx + 0)(Column.columnToUUID),
        `type` = row(idx + 1)(Column.columnToString),
        payload = row(idx + 2)(TypoJsonb.column),
        status = row(idx + 3)(Column.columnToString),
        statusDetails = row(idx + 4)(Column.columnToOption(Column.columnToString)),
        errorCount = row(idx + 5)(Column.columnToOption(Column.columnToInt)),
        executeAt = row(idx + 6)(Implicits.instantColumn),
        createdAt = row(idx + 7)(Implicits.instantColumn),
        updatedAt = row(idx + 8)(Implicits.instantColumn)
      )
    )
  }
  implicit lazy val writes: OWrites[BackgroundJobsRow] = OWrites[BackgroundJobsRow](o =>
    new JsObject(
      ListMap[String, JsValue](
        "background_job_id" -> Writes.UuidWrites.writes(o.backgroundJobId),
        "type" -> Writes.StringWrites.writes(o.`type`),
        "payload" -> TypoJsonb.writes.writes(o.payload),
        "status" -> Writes.StringWrites.writes(o.status),
        "status_details" -> Writes.OptionWrites(Writes.StringWrites).writes(o.statusDetails),
        "error_count" -> Writes.OptionWrites(Writes.IntWrites).writes(o.errorCount),
        "execute_at" -> implicitly[Writes[Instant]].writes(o.executeAt),
        "created_at" -> implicitly[Writes[Instant]].writes(o.createdAt),
        "updated_at" -> implicitly[Writes[Instant]].writes(o.updatedAt)
      )
    )
  )
}
