/** File has been automatically generated by `typo`.
  *
  * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
  */
package net
package wiringbits
package typo_generated
package public
package background_jobs

import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import net.wiringbits.typo_generated.customtypes.TypoUUID
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typo.dsl.Bijection

/** Type for the primary key of table `public.background_jobs` */
case class BackgroundJobsId(value: TypoUUID) extends AnyVal
object BackgroundJobsId {
  implicit lazy val arrayColumn: Column[Array[BackgroundJobsId]] = Column.columnToArray(column, implicitly)
  implicit lazy val arrayToStatement: ToStatement[Array[BackgroundJobsId]] =
    TypoUUID.arrayToStatement.contramap(_.map(_.value))
  implicit lazy val bijection: Bijection[BackgroundJobsId, TypoUUID] =
    Bijection[BackgroundJobsId, TypoUUID](_.value)(BackgroundJobsId.apply)
  implicit lazy val column: Column[BackgroundJobsId] = TypoUUID.column.map(BackgroundJobsId.apply)
  implicit def ordering(implicit O0: Ordering[TypoUUID]): Ordering[BackgroundJobsId] = Ordering.by(_.value)
  implicit lazy val parameterMetadata: ParameterMetaData[BackgroundJobsId] = new ParameterMetaData[BackgroundJobsId] {
    override def sqlType: String = TypoUUID.parameterMetadata.sqlType
    override def jdbcType: Int = TypoUUID.parameterMetadata.jdbcType
  }
  implicit lazy val reads: Reads[BackgroundJobsId] = TypoUUID.reads.map(BackgroundJobsId.apply)
  implicit lazy val toStatement: ToStatement[BackgroundJobsId] = TypoUUID.toStatement.contramap(_.value)
  implicit lazy val writes: Writes[BackgroundJobsId] = TypoUUID.writes.contramap(_.value)
}
