/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package net
package wiringbits
package typo
package public
package background_jobs

import net.wiringbits.typo.customtypes.TypoJsonb
import net.wiringbits.typo.customtypes.TypoOffsetDateTime
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLikeNoHkt
import typo.dsl.SqlExpr.IdField
import typo.dsl.SqlExpr.OptField
import typo.dsl.Structure.Relation

class BackgroundJobsStructure[Row](val prefix: Option[String], val extract: Row => BackgroundJobsRow, val merge: (Row, BackgroundJobsRow) => Row)
  extends Relation[BackgroundJobsFields, BackgroundJobsRow, Row]
    with BackgroundJobsFields[Row] { outer =>

  override val backgroundJobId = new IdField[BackgroundJobsId, Row](prefix, "background_job_id", None, Some("uuid"))(x => extract(x).backgroundJobId, (row, value) => merge(row, extract(row).copy(backgroundJobId = value)))
  override val `type` = new Field[String, Row](prefix, "type", None, None)(x => extract(x).`type`, (row, value) => merge(row, extract(row).copy(`type` = value)))
  override val payload = new Field[TypoJsonb, Row](prefix, "payload", None, Some("jsonb"))(x => extract(x).payload, (row, value) => merge(row, extract(row).copy(payload = value)))
  override val status = new Field[String, Row](prefix, "status", None, None)(x => extract(x).status, (row, value) => merge(row, extract(row).copy(status = value)))
  override val statusDetails = new OptField[String, Row](prefix, "status_details", None, None)(x => extract(x).statusDetails, (row, value) => merge(row, extract(row).copy(statusDetails = value)))
  override val errorCount = new OptField[Int, Row](prefix, "error_count", None, Some("int4"))(x => extract(x).errorCount, (row, value) => merge(row, extract(row).copy(errorCount = value)))
  override val executeAt = new Field[TypoOffsetDateTime, Row](prefix, "execute_at", Some("text"), Some("timestamptz"))(x => extract(x).executeAt, (row, value) => merge(row, extract(row).copy(executeAt = value)))
  override val createdAt = new Field[TypoOffsetDateTime, Row](prefix, "created_at", Some("text"), Some("timestamptz"))(x => extract(x).createdAt, (row, value) => merge(row, extract(row).copy(createdAt = value)))
  override val updatedAt = new Field[TypoOffsetDateTime, Row](prefix, "updated_at", Some("text"), Some("timestamptz"))(x => extract(x).updatedAt, (row, value) => merge(row, extract(row).copy(updatedAt = value)))

  override val columns: List[FieldLikeNoHkt[?, Row]] =
    List[FieldLikeNoHkt[?, Row]](backgroundJobId, `type`, payload, status, statusDetails, errorCount, executeAt, createdAt, updatedAt)

  override def copy[NewRow](prefix: Option[String], extract: NewRow => BackgroundJobsRow, merge: (NewRow, BackgroundJobsRow) => NewRow): BackgroundJobsStructure[NewRow] =
    new BackgroundJobsStructure(prefix, extract, merge)
}
